export default {
    'WELCOME': 'Witaj',
    'TICKETS': 'Zgłoszenia',
    'ARTICLES': 'Artykuły',
    'ACCOUNT': 'Konto',
    'SUBMIT': 'Wyślij',
    'EMAIL': 'Email',
    'PASSWORD': 'Hasło',
    'REPEAT_PASSWORD': 'Powtórz hasło',
    'LOG_IN': 'Zaloguj się',
    'SIGN_UP': 'Zarejestruj się',
    'FORGOT_PASSWORD': 'Zapomniałeś swoje hasło ?',
    'RECOVER_PASSWORD': 'Odzyskiwanie hasła',
    'RECOVER_SENT': 'Wysłano wiadomość e-mail z instrukcjami odzyskiwania.',
    'NEW_EMAIL': 'Nowy email',
    'FULL_NAME': 'Pełne imię i nazwisko',
    'OLD_PASSWORD': 'Stare hasło',
    'NEW_PASSWORD': 'Nowe hasło',
    'REPEAT_NEW_PASSWORD': 'Powtórz nowe hasło',
    'BACK_LOGIN_FORM': 'Powrót do formularza logowania',
    'VIEW_ARTICLES': 'Zobacz artykuły',
    'EDIT_PROFILE': 'Edytuj profil',
    'CLOSE_SESSION': 'Zamknij sesję',
    'CREATE_TICKET': 'Utwórz zgłoszenie',
    'TICKET_LIST': 'Lista zgłoszeń',
    'SUPPORT_CENTER': 'Centrum wsparcia',
    'DEPARTMENT': 'Department',
    'AUTHOR': 'Autor',
    'DATE': 'Data',
    'RESPOND': 'Odpowiedź',
    'RESPOND_TICKET': 'Odpowiedz na zgłoszenie',
    'CLOSE_TICKET': 'Zamknij zgłoszenie',
    'DELETE_TICKET': 'Usuń zgłoszenie',
    'NO_ATTACHMENT': 'Nie załączono pliku',
    'STAFF': 'Personel',
    'CUSTOMER': 'Klient',
    'YES': 'Tak',
    'NO': 'Nie',
    'CANCEL': 'Anuluj',
    'MY_ACCOUNT': 'Moje konto',
    'DASHBOARD': 'Tablica',
    'USERS': 'Klienci',
    'SETTINGS': 'Ustawienia',
    'STATISTICS': 'Statystyki',
    'LAST_ACTIVITY': 'Ostatnia aktywność',
    'MY_TICKETS': 'Moje zgłoszenia',
    'NEW_TICKETS': 'Nowe zgłoszenia',
    'ALL_TICKETS': 'Wszystkie zgłoszenia',
    'CUSTOM_RESPONSES': 'Odpowiedzi niestandardowe',
    'CUSTOM_TAGS': 'Tagi użytkowników',
    'LIST_USERS': 'Lista użytkowników',
    'BAN_USERS': 'Bany użytkowników',
    'LIST_ARTICLES': 'Lista artykułów',
    'STAFF_MEMBERS': 'Członkowie zespołu',
    'DEPARTMENTS': 'Departmenty',
    'SYSTEM_PREFERENCES': 'Ustawienia systemu',
    'ADVANCED_SETTINGS': 'Zaawansowane ustawienia',
    'EMAIL_TEMPLATES': 'Szablony email',
    'FILTERS_CUSTOM_FIELDS': 'Filtry i pola niestandardowe',
    'PRIORITY': 'Priorytety',
    'NUMBER': 'Numer',
    'HIGH': 'Wysoki',
    'MEDIUM': 'Średni',
    'LOW': 'Niski',
    'TITLE': 'Tytuł',
    'CONTENT': 'Zawartość',
    'SAVE': 'Zapisz',
    'DISCARD_CHANGES': 'Porzuć zmiany',
    'DELETE': 'Usuń',
    'LANGUAGE': 'Język',
    'OWNER': 'Właściciel',
    'OWNED': 'Własność',
    'STATUS': 'Status',
    'NONE': 'Żaden',
    'OPENED': 'Otwarte',
    'CLOSED': 'Zamknięte',
    'CLOSE': 'Zamknij',
    'RE_OPEN': 'Otwórz ponownie',
    'ASSIGN_TO_ME': 'Przypisz do mnie',
    'UN_ASSIGN': 'Usuń przypisanie',
    'VIEW_TICKET': 'Pokaż zgłoszenie',
    'VIEW_TICKET_DESCRIPTION': 'Sprawdź status zgłoszenia za pomocą numeru i wiadomości e-mail.',
    'SELECT_CUSTOM_RESPONSE': 'Wybierz odpowiedź...',
    'WARNING': 'Ostrzeżenie',
    'INFO': 'Informacja',
    'ALL_DEPARTMENTS': 'Wszystkie departamenty',
    'EMAIL_BANNED': 'Zablokowane adresy email',
    'UN_BAN': 'Wyłącz blokadę',
    'BAN_NEW_EMAIL': 'Zablokuj nowy adres email',
    'BAN_EMAIL': 'Zablokuj email',
    'EDIT_EMAIL': 'Edytuj email',
    'EDIT_PASSWORD': 'Edytuj hasło',
    'CHANGE_EMAIL': 'Zmień email',
    'CHANGE_PASSWORD': 'Zmień hasło',
    'NAME': 'Nazwa',
    'SIGNUP_DATE': 'Data rejestracji',
    'SEARCH_USERS': 'Szukaj użytkownika...',
    'SEARCH_EMAIL': 'Szukaj adresu email...',
    'USER_VIEW_TITLE': 'Użytkownik #{userId}',
    'EDIT_TOPIC': 'Edytuj temat',
    'ADD_TOPIC': 'Dodaj temat',
    'ICON': 'Ikona',
    'COLOR': 'Kolor',
    'ADD_NEW_ARTICLE': 'Dodaj nowy artykuł',
    'ADD_ARTICLE': 'Dodaj artykuł',
    'LAST_EDITED_IN': 'Ostatnia edycja {date}',
    'EDIT': 'Edytuj',
    'ADD_CUSTOM_TAG': 'Dodaj tag użytkownika',
    'NO_RESULTS': 'Brak wyników',
    'DELETE_AND_BAN': 'Usuń i zablokuj',
    'STAFF_LEVEL': 'Poziom personelu',
    'ASSIGNED': 'Przypisany',
    'ASSIGNED_TICKETS': '{tickets} przypisanych zgłoszeń',
    'CLOSED_TICKETS': '{tickets} zamkniętych zgłoszeń',
    'LAST_LOGIN': 'Ostatnio zalogowany',
    'ADD_NEW_STAFF': 'Dodaj nowy personel',
    'ADD_STAFF': 'Dodaj personel',
    'LEVEL': 'Poziom',
    'LEVEL_1': 'Poziom 1 (zgłoszenia)',
    'LEVEL_2': 'Poziom 2 (zgłoszenia + artykuły)',
    'LEVEL_3': 'Poziom 3 (zgłoszenia + artykuły + personel)',
    'LEVEL_1_DESCRIPTION': 'dostęp do zgłoszeń oraz użytkowników.',
    'LEVEL_2_DESCRIPTION': 'poziom 1 oraz tworzenie i edytowanie artykułów i niestandardowych odpowiedzi.',
    'LEVEL_3_DESCRIPTION': 'poziom 1, 2 oraz tworzenie / edytowanie personelu i zarządzanie systemem.',
    'UPDATE_EMAIL': 'Aktualizuj email',
    'UPDATE_PASSWORD': 'Aktualizuj hasło',
    'UPDATE_LEVEL': 'Aktualizuj poziom',
    'UPDATE_DEPARTMENTS': 'Aktualizuj departament',
    'EDIT_STAFF': 'Edytuj członka personelu',
    'ADD_DEPARTMENT': 'Dodaj departament',
    'UPDATE_DEPARTMENT': 'Aktualizuj departament',
    'TRANSFER_TICKETS_TO': 'Przenieś zgłoszenie do',
    'COMMENTS': 'Komentarze',
    'DELETE_STAFF_MEMBER': 'Usuń członka personelu',
    'MAINTENANCE_MODE': 'Tryb konderwacji',
    'MAINTENANCE_MODE_INFO': 'Trwa konserwacja, system czasowo wyłaczony.',
    'RECOVER_DEFAULT': 'Przywróc domyślne',
    'SUPPORT_CENTER_URL': 'Adres URL',
    'SUPPORT_CENTER_TITLE': 'Tutył systemu zgłoszeń',
    'SUPPORT_CENTER_LAYOUT': 'Wygląd systemu zgłoszeń',
    'DEFAULT_TIMEZONE': 'Domyślna strefa czasowa (GMT)',
    'NOREPLY_EMAIL': 'Adres email bez odpowiedzi (Noreplay)',
    'SMTP_USER': 'Użytkownik SMTP',
    'SMTP_SERVER': 'Serwer SMTP',
    'SMTP_PASSWORD': 'Hasło SMTP',
    'IMAP_USER': 'Użytkownik IMAP',
    'IMAP_SERVER': 'Serwer IMAP',
    'IMAP_PASSWORD': 'Hasło IMAP',
    'IMAP_TOKEN': 'Token IMAP',
    'IMAP_TOKEN_DESCRIPTION': 'Użyj tego tokena do uwierzytelnienia żądania odpytywania.',
    'PORT': 'Port',
    'RECAPTCHA_PUBLIC_KEY': 'Recaptcha Public Key',
    'RECAPTCHA_PRIVATE_KEY': 'Recaptcha Private Key',
    'ALLOW_FILE_ATTACHMENTS': 'Dozwolone załączniki',
    'MAX_SIZE_MB': 'Maksymalna wielkość (MB)',
    'UPDATE_SETTINGS': 'Ustawienia wysyłania',
    'DEFAULT_LANGUAGE': 'Domyślny język',
    'SUPPORTED_LANGUAGES': 'Wspierane języki',
    'SUPPORTED_LANGUAGES_INFO': 'Obsługiwane języki to języki, w których można zapisywać zgłoszenia.',
    'ALLOWED_LANGUAGES': 'Dozwolone języki',
    'ALLOWED_LANGUAGES_INFO': 'Dozwolone języki to języki, które mogą być używane przez użytkownika.',
    'SETTINGS_UPDATED': 'Ustawienia zostały zaktualizowane',
    'ON': 'On',
    'OFF': 'Off',
    'BOXED': 'Zapakowane',
    'FULL_WIDTH': 'Pełna szerokość',
    'LOAD_MORE': 'Pokaż więcej',
    'MY_NOTIFICATIONS': 'Moje powiadomienia',
    'ALL_NOTIFICATIONS': 'Wszystkie powiadomienia',
    'VERIFY_SUCCESS': 'Użytkownik zweryfikowany',
    'VERIFY_FAILED': 'Nie można zweryfikować',
    'ENABLE_USER_SYSTEM': 'Użyj systemu użytkownika dla klientów',
    'ENABLE_USER_REGISTRATION': 'Włącz rejestrację użytkowników',
    'INCLUDE_USERS_VIA_CSV': 'Importuj użytkowników z pliku CSV',
    'BACKUP_DATABASE': 'Kopia bazy danych',
    'DELETE_ALL_USERS': 'Usuń wszystkich użytkowników',
    'PLEASE_CONFIRM_PASSWORD': 'Proszę potwierdź Twoim hasłem przed zmianą ustawień',
    'REGISTRATION_API_KEYS': 'Zarejestruj klucz API',
    'NAME_OF_KEY': 'Nazwa klucza',
    'KEY': 'Klucz',
    'ADD_API_KEY': 'Dodaj klucz API',
    'NO_KEY_SELECTED': 'Nie wybrano klucza',
    'CHECK_TICKET': 'Sprawdź zgłoszenie',
    'ACTIVITY': 'Aktywne',
    'HOME': 'Start',
    'TICKET_NUMBER': 'Zgłoszenie numer',
    'NEXT': 'Następny',
    'SUBJECT': 'Temat',
    'SEND_EMAIL_ON_NEW_TICKET': 'Wyślij wiadomość email przy nowym zgłoszeniu',
    'STAFF_UPDATED': 'Członek personelu został zaktualizowany',
    'UPDATE': 'Aktualizuj',
    'NEVER': 'Nigdy',
    'HIMSELF': 'himself',
    'ADD_USER': 'Dodaj używkownika',
    'UPLOAD_FILE': 'Wyślij plik',
    'PRIVATE': 'Prywatne',
    'ENABLE_USER': 'Włącz użytkownika',
    'DISABLE_USER': 'Wyłącz użytkownika',
    'SHOW_CLOSED_TICKETS': 'Pokaż wszystkie zamknięte zgłoszenia',
    'IMAGE_HEADER_URL': 'Zdjęcie nagłówka (URL)',
    'IMAGE_HEADER_DESCRIPTION': 'Image that will be used as header of the email',
    'EMAIL_SETTINGS': 'Konfiguracje email',
    'ADDITIONAL_FIELDS': 'Dodatkowe pola',
    'NEW_CUSTOM_FIELD': 'Nowe pole niestandardowe',
    'TYPE': 'Typ',
    'SELECT_INPUT': 'Wybierz wejście',
    'TEXT_INPUT': 'Tekstowe wejście',
    'OPTION': 'Opcje {index}',
    'OPTIONS': 'Opcje',
    'FIELD_DESCRIPTION': 'Opis pola (opcjonalnie)',
    'DESCRIPTION_ADD_CUSTOM_TAG': 'tutaj możesz dodać nowy niestandardowy tag',
    'CUSTOM_FIELDS': 'Pola niestandardowe',

    'CHART_CREATE_TICKET': 'Zgłoszenie utworzone',
    'CHART_CLOSE': 'Zgłoszenia zamknięte',
    'CHART_SIGNUP': 'Zapisy',
    'CHART_COMMENT': 'Odpowiedzi',
    'CHART_ASSIGN': 'Przydzielony',

    //ACTIVITIES
    'ACTIVITY_COMMENT': 'komentarze zgłoszeń',
    'ACTIVITY_ASSIGN': 'przydzielone zgłoszenia',
    'ACTIVITY_UN_ASSIGN': 'nie przydzielone zgłoszenia',
    'ACTIVITY_CLOSE': 'zamknięte zgłoszenia',
    'ACTIVITY_CREATE_TICKET': 'stwórz zgłoszenie',
    'ACTIVITY_RE_OPEN': 'ponownie otworzone zgłoszenie',
    'ACTIVITY_DEPARTMENT_CHANGED': 'zmień departament zgłoszenia',
    'ACTIVITY_PRIORITY_CHANGED': 'zmień priorytet zgłoszenia',

    'ACTIVITY_EDIT_SETTINGS': 'edytowano ustawienia',
    'ACTIVITY_SIGNUP': 'zalogowano',
    'ACTIVITY_ADD_TOPIC': 'dodano temat',
    'ACTIVITY_ADD_ARTICLE': 'dodano artykuł',
    'ACTIVITY_DELETE_TOPIC': 'usunięto temat',
    'ACTIVITY_DELETE_ARTICLE': 'usunięto artykuł',
    'ACTIVITY_EDIT_ARTICLE': 'edytowano artykuł',
    'ACTIVITY_ADD_STAFF': 'dodano personel',
    'ACTIVITY_ADD_DEPARTMENT': 'dodano departament',
    'ACTIVITY_DELETE_DEPARTMENT': 'usunięto department',
    'ACTIVITY_EDIT_DEPARTMENT': 'edytowano department',
    'ACTIVITY_ADD_CUSTOM_RESPONSE': 'dodano niestandardową odpowiedź',
    'ACTIVITY_DELETE_CUSTOM_RESPONSE': 'usunięto niestandardową odpowiedź',
    'ACTIVITY_EDIT_CUSTOM_RESPONSE': 'edytowana odpowiedź niestandardowa',
    'ACTIVITY_BAN_USER': 'uzytkownik zablokowany',
    'ACTIVITY_DELETE_USER': 'użytkownik usunięty',
    'ACTIVITY_UN_BAN_USER': 'użytkownik odblokowany',

    'SERVER_REQUIREMENTS': 'Wymagania serwera',
    'DATABASE_CONFIGURATION': 'Konfiguracja bazy danych',
    'ADMIN_SETUP': 'Konfiguracja administratora',
    'COMPLETED': 'Zakończono',
    'INSTALL_HEADER_TITLE': 'Kreator konfiguracji OpenSupports',
    'INSTALL_HEADER_DESCRIPTION': 'Ten kreator pomoże Ci skonfigurować i zainstalować OpenSupport na Twoim serwerze',
    'SELECT_LANGUAGE': 'Wybierz język',
    'REQUIREMENT': 'Wymagania',
    'VALUE': 'Wartość',
    'REFRESH': 'Odśwież',
    'USER_SYSTEM': 'Użytkownik systemowy',
    'PREVIOUS': 'Poprzedni',
    'DATABASE_HOST': 'MySQL server',
    'DATABASE_PORT': 'MySQL server port',
    'DATABASE_NAME': 'MySQL baza danych',
    'DATABASE_USER': 'MySQL użytkownik',
    'DATABASE_PASSWORD': 'MySQL hasło',
    'ADMIN_NAME': 'Nazwa konta administratora',
    'ADMIN_EMAIL': 'Email administratora',
    'ADMIN_PASSWORD': 'Hasło administratora',
    'ADMIN_PASSWORD_DESCRIPTION': 'Proszę zapamiętać  hasło. Jest potrzebne do uzyskania dostępu do panelu administracyjnego. Możesz je zmienić później.',
    'INSTALLATION_COMPLETED': 'Instalacja kompletna.',
    'INSTALLATION_COMPLETED_DESCRIPTION': 'Instalacja aplikacji OpenSupports jest kompletna, następi przeniesienie do panelu administracyjnego.',

    'STEP_TITLE': 'Krok {current} z {total} - {title}',
    'STEP_1_DESCRIPTION': 'Wybierz preferowany przez Ciebie język kreatora instalacji.',
    'STEP_2_DESCRIPTION': 'Poniżej wymieniono wymagania dotyczące uruchamiania OpenSupports. Upewnij się, że wszystkie wymagania są spełnione.',
    'STEP_3_DESCRIPTION': 'Proszę wypełnić konfigurację bazy danych MySQL.',
    'STEP_4_DESCRIPTION': 'Wybierz preferencje systemu użytkownika.',
    'STEP_5_DESCRIPTION': 'Proszę wypełnić swoje ogólne preferencje systemowe.',
    'STEP_6_DESCRIPTION': 'Proszę skonfigurować konto administratora.',
    'STEP_7_DESCRIPTION': 'Instalacja została zakończona',

    //VIEW DESCRIPTIONS
    'CREATE_TICKET_DESCRIPTION': 'To jest formularz do tworzenia zgłoszeń. Wypełnij formularz i prześlij nam swoje problemy / wątpliwości / sugestie. Nasz system wsparcia odpowie na nie jak najszybciej.',
    'TICKET_LIST_DESCRIPTION': 'Tutaj znajdziesz listę wszystkich zgłoszeń, które wysłałeś do naszego zespołu pomocy technicznej.',
    'TICKETS_DESCRIPTION': 'Wyślij zgłoszenie za pośrednictwem naszego centrum pomocy technicznej i uzyskaj odpowiedź na swoje wątpliwości, sugestie i problemy.',
    'ARTICLES_DESCRIPTION': 'Zapoznaj się z naszymi artykułami na temat wspólnych problemów, przewodników i dokumentacji.',
    'ACCOUNT_DESCRIPTION': 'Wszystkie Twoje zgłoszenia są przechowywane w profilu Twojego konta. Śledź wszystkie swoje zgłoszenia wysyłane do naszego zespołu pracowników.',
    'SUPPORT_CENTER_DESCRIPTION': 'Witamy w centrum pomocy technicznej. Możesz skontaktować się z nami za pośrednictwem systemu zgłoszeń. Twoje zgłoszenia zostaną odebrane przez nasz personel.',
    'CUSTOM_RESPONSES_DESCRIPTION': 'Niestandardowe odpowiedzi to automatyczne odpowiedzi na typowe problemy',
    'CUSTOM_TAGS_DESCRIPTION': 'Tutaj możesz wyświetlić zarządzające niestandardowe tagi zgłoszeń, aby lepiej je zidentyfikować',
    'MY_TICKETS_DESCRIPTION': 'Tutaj możesz zobaczyć zgłoszenia, za które jesteś odpowiedzialny.',
    'NEW_TICKETS_DESCRIPTION': 'Tutaj możesz zobaczyć wszystkie nowe zgłoszenia, które nie zostały przydzielone przez nikogo.',
    'ALL_TICKETS_DESCRIPTION': 'Tutaj możesz zobaczyć zgłoszenia wydziałów, do których jesteś przydzielony.',
    'TICKET_VIEW_DESCRIPTION': 'Te zgłoszenie zostao wysłane przez klienta. Tutaj możesz odpowiedzieć lub przypisać zgłoszenia',
    'BAN_USERS_DESCRIPTION': 'Tutaj możesz zobaczyć listę zbanowanych wiadomości e-mail, możesz je banować lub dodać więcej e-maili do listy.',
    'LIST_USERS_DESCRIPTION': 'To jest lista użytkowników zarejestrowanych na tej platformie. Możesz wyszukać kogoś, usunąć  lub zablokować. ',
    'USER_VIEW_DESCRIPTION': 'Tutaj możesz znaleźć wszystkie informacje o użytkowniku i wszystkich zgłoszeniach wysłanych przez użytkownika. Możesz je także usunąć lub zablokować. ',
    'DELETE_USER_DESCRIPTION': 'Użytkownik nie będzie mógł się zalogować, a wszystkie jego zgłoszenia zostaną usunięte. Ponadto e-mail nie może być już używany.',
    'DELETE_TOPIC_DESCRIPTION': 'Usuwając temat, wszystkie artykuły związane z nim zostaną usunięte.',
    'EDIT_TOPIC_DESCRIPTION': 'Tutaj możesz zmienić nazwę, ikonę i kolor ikony tematu.',
    'ADD_ARTICLE_DESCRIPTION': 'Tutaj możesz dodać artykuł, który będzie dostępny dla każdego użytkownika. Zostanie on dodany w kategorii {category}. ',
    'LIST_ARTICLES_DESCRIPTION': 'To jest lista artykułów, które zawierają informacje o naszych usługach.',
    'ADD_TOPIC_DESCRIPTION': 'Tutaj możesz dodać temat, który działa jako kategoria artykułów.',
    'DELETE_ARTICLE_DESCRIPTION': 'Zamierzasz usunąć ten artykuł na zawsze.',
    'STAFF_MEMBERS_DESCRIPTION': 'Tutaj możesz zobaczyć, kto jest twoim pracownikiem.',
    'ADD_STAFF_DESCRIPTION': 'Tutaj możesz dodać członków personelu do swoich zespołów',
    'EDIT_STAFF_DESCRIPTION': 'Tutaj możesz edytować informacje o członku personelu.',
    'MY_ACCOUNT_DESCRIPTION': 'Tutaj możesz edytować informacje o sobie.',
    'DEPARTMENTS_DESCRIPTION': 'Dział to grupa, do której mogą przejść zgłoszenia. Służą do kategoryzacji zgłoszeń. Możesz przypisać je innym członkom personelu.',
    'MAINTENANCE_MODE_DESCRIPTION': 'System wsparcia jest w trybie konserwacji, a więc w tej chwili niedostępny. Wrócimy jak najszybciej. ',
    'EMAIL_TEMPLATES_DESCRIPTION': 'Tutaj możesz edytować szablony wiadomości e-mail, które będą wysyłane do użytkowników. Pamiętaj, że nawiasy klamrowe w podwójnych nawiasach wskazują wartość zmiennej. Na przykład \'name\' reprezentuje nazwę użytkownika.',
    'SYSTEM_PREFERENCES_DESCRIPTION': 'Tutaj możesz edytować preferencje systemu.',
    'VERIFY_SUCCESS_DESCRIPTION': 'Użytkownik został poprawnie zweryfikowany. Możesz się teraz zalogować.',
    'VERIFY_FAILED_DESCRIPTION': 'Nie można było zweryfikować.',
    'STATISTICS_DESCRIPTION': 'Tutaj możesz wyświetlić statystyki związane ze zgłoszeniami i rejestracjami.',
    'ADVANCED_SETTINGS_DESCRIPTION': 'Tutaj możesz zmienić zaawansowane ustawienia swojego systemu. Uważaj, zmian których dokonujesz, nie można odwrócić. ',
    'USER_SYSTEM_DISABLED': 'System użytkownika został wyłączony',
    'USER_SYSTEM_ENABLED': 'System użytkownika został włączony',
    'REGISTRATION_DISABLED': 'Rejestracja została wyłączona',
    'REGISTRATION_ENABLED': 'Rejestracja została włączona',
    'ADD_API_KEY_DESCRIPTION': 'Wstaw nazwę i wygenerowany zostanie klucz API rejestracji'.
    'SIGN_UP_VIEW_DESCRIPTION': 'Tutaj możesz utworzyć konto dla centrum wsparcia. Wymagane jest wysłanie zgłoszenia i zapoznanie się z dokumentacją. ',
    'EDIT_PROFILE_VIEW_DESCRIPTION': 'Tutaj możesz edytować użytkownika, zmieniając adres e-mail lub hasło.',
    'ENABLE_USER_SYSTEM_DESCRIPTION': 'Włącz/wyłącz korzystanie z systemu użytkownika. Jeśli go wyłączysz, wszyscy użytkownicy zostaną usunięci, ale zgłoszenia zostaną zachowane. Jeśli go włączysz, zostaną stworzeni użytkownicy istniejących zgłoszeń.',
    'CSV_DESCRIPTION': 'Plik CSV musi mieć 3 kolumny: e-mail, hasło, nazwę. Nie ma limitu liczby wierszy. Zostanie utworzony jeden użytkownik na jeden wiersz pliku. ',
    'SMTP_SERVER_DESCRIPTION': 'Konfiguracja serwera SMTP pozwala aplikacji na wysyłanie wiadomości e-mail. Jeśli go nie skonfigurujesz, żadne wiadomości e-mail nie zostaną wysłane przez OpenSupports. ',
    'IMAP_SERVER_DESCRIPTION': 'Konfiguracja serwera IMAP pozwala aplikacji na tworzenie zgłoszeń z wiadomości e-mail wysyłanych do skrzynki pocztowej.',
    'ENABLE_USER_DESCRIPTION': 'Ta akcja pozwala użytkownikowi zalogować się i utworzyć zgłoszenie.',
    'DISABLE_USER_DESCRIPTION': 'Użytkownik zostanie wyłączony i nie będzie mógł się zalogować i utworzyć zgłoszeń.',
    'PRIVATE_RESPONSE_DESCRIPTION': 'Ta odpowiedź będzie widoczna tylko dla pracowników',
    'PRIVATE_TOPIC_DESCRIPTION': 'Ten temat będzie widoczny tylko dla pracowników',
    'PRIVATE_DEPARTMENT_DESCRIPTION': 'Ten dział będzie widoczny tylko dla pracowników',
    'EMAIL_SETTINGS_DESCRIPTION': 'Tutaj możesz edytować ustawienia otrzymywania i wysyłania wiadomości e-mail do klientów.',
    'IMAP_POLLING_DESCRIPTION': 'Sprawdzanie skrzynki odbiorczej nie będzie wykonywane automatycznie przez OpenSupports. Aby przetwarzać wiadomości e-mail, musisz okresowo wysyłać żądania POST do tego adresu URL: {url} ',
    'NEW_CUSTOM_FIELD_DESCRIPTION': 'Tutaj możesz utworzyć niestandardowe pole dla użytkownika, może to być puste pole tekstowe lub stały zestaw opcji.',
    'CUSTOM_FIELDS_DESCRIPTION': 'Pola niestandardowe to dodatkowe pola, które użytkownicy mogą wypełnić, aby uzyskać więcej informacji na ich temat.',

    //ERRORS
    'EMAIL_OR_PASSWORD': 'Email or password invalid',
    'EMAIL_NOT_EXIST': 'Email does not exist',
    'ERROR_EMPTY': 'Invalid value',
    'ERROR_PASSWORD': 'Invalid password',
    'ERROR_NAME': 'Invalid name',
    'ERROR_TITLE': 'Invalid title',
    'ERROR_EMAIL': 'Invalid email',
    'ERROR_CONTENT_SHORT': 'Content too short',
    'PASSWORD_NOT_MATCH': 'Password does not match',
    'INVALID_RECOVER': 'Invalid recover data',
    'TICKET_SENT_ERROR': 'An error occurred while trying to create the ticket.',
    'TICKET_COMMENT_ERROR': 'An error occurred while trying to add the comment.',
    'NO_PERMISSION': 'You\'ve no permission to access to this page.',
    'INVALID_USER': 'User id is invalid',
    'ERROR_RETRIEVING_TICKETS': 'An error occurred while trying to retrieve tickets.',
    'ERROR_RETRIEVING_USERS': 'An error occurred while trying to retrieve users.',
    'ERROR_RETRIEVING_BAN_LIST': 'An error occurred while trying to retrieve the list of banned emails.',
    'ERROR_BANNING_EMAIL': 'An error occurred while trying to ban the email.',
    'ERROR_RETRIEVING_ARTICLES': 'An error occurred while trying to retrieve articles.',
    'ERROR_LIST': 'Select at least one',
    'ERROR_URL': 'Invalid URL',
    'UNVERIFIED_EMAIL': 'Email is not verified yet',
    'ERROR_UPDATING_SETTINGS': 'An error occurred while trying to update settings',
    'INVALID_EMAIL_OR_TICKET_NUMBER': 'Invalid email or ticket number',
    'INVALID_FILE': 'Invalid file',
    'ERRORS_FOUND': 'Errors found',
    'ERROR_IMAGE_SIZE': 'No image can have a size greater than {size} MB',
    'USER_DISABLED': 'This account is disabled.',
    'INVALID_SYNTAX': 'Invalid syntax.',
    'DEPARTMENT_PRIVATE_TICKETS': 'This department has tickets created by non-staff and it can not be private',
    'CURRENTLY_UNAVAILABLE': 'Currently unavailable',

    //MESSAGES
    'SIGNUP_SUCCESS': 'You have registered successfully in our support system.',
    'TICKET_SENT': 'Ticket has been created successfully.',
    'VALID_RECOVER': 'Password recovered successfully',
    'EMAIL_EXISTS': 'Email already exists',
    'ARE_YOU_SURE': 'Confirm action',
    'EMAIL_WILL_CHANGE': 'The current email will be changed',
    'PASSWORD_WILL_CHANGE': 'The current password will be changed',
    'EMAIL_CHANGED': 'Email has been changed successfully',
    'PASSWORD_CHANGED': 'Password has been changed successfully',
    'OLD_PASSWORD_INCORRECT': 'Old password is incorrect',
    'WILL_LOSE_CHANGES': 'You haven\'t save. Your changes will be lost.',
    'WILL_DELETE_CUSTOM_RESPONSE': 'The custom response will be deleted.',
    'WILL_DELETE_DEPARTMENT': 'The department will be deleted. All the tickets will be transfer to the department selected.',
    'NO_STAFF_ASSIGNED': 'No staff member is assigned to this department.',
    'NO_DEPARTMENT_ASSIGNED': 'No ticket department is assigned you.',
    'LEVEL_UPDATED': 'Level has been updated successfully.',
    'DEPARTMENTS_UPDATED': 'Departments have been updated successfully.',
    'FAILED_EDIT_STAFF': 'An error occurred while trying to edit staff member.',
    'EMAIL_BANNED_SUCCESSFULLY': 'Email has been banned successfully',
    'WILL_DELETE_STAFF': 'This staff member will be deleted and all its tickets will be unassigned.',
    'WILL_RECOVER_EMAIL_TEMPLATE': 'This email template will be recover to it\'s default value on this language.',
    'SUCCESS_IMPORTING_CSV_DESCRIPTION': 'CSV File has been imported successfully',
    'SUCCESS_DELETING_ALL_USERS': 'Users have beend deleted successfully',
    'SUCCESSFUL_CONNECTION': 'Successful connection',
    'UNSUCCESSFUL_CONNECTION': 'Unsuccessful connection',
    'SERVER_CREDENTIALS_WORKING': 'Server credentials are working correctly',
    'DELETE_CUSTOM_FIELD_SURE': 'Some users may be using this field. Are you sure you want to delete it?',

    'LAST_7_DAYS': 'Ostatnie 7 dni',
    'LAST_30_DAYS': 'Ostatnie 30 dni',
    'LAST_90_DAYS': 'Ostatnie 90 dni',
    'LAST_365_DAYS': 'Ostatnie 365 dni',

    'TEST': 'Test',
    'ACTIVITY_COMMENT_THIS': 'commented this ticket',
    'ACTIVITY_ASSIGN_THIS': 'assigned this ticket to',
    'ACTIVITY_UN_ASSIGN_THIS': 'unassigned this ticket to',
    'ACTIVITY_CLOSE_THIS': 'closed this ticket',
    'ACTIVITY_CREATE_TICKET_THIS': 'created this ticket',
    'ACTIVITY_RE_OPEN_THIS': 'reopened this ticket',
    'ACTIVITY_DEPARTMENT_CHANGED_THIS': 'changed department of this ticket to ',
    'ACTIVITY_PRIORITY_CHANGED_THIS': 'changed priority of this ticket to',
    'DATE_PREFIX': 'on',
    'LEFT_EMPTY_DATABASE': 'Zostaw pusty jeśli mam utworzyć pustą bazę danych automatycznie',
    'DEFAULT_PORT': 'Zostaw pusty jeśli port jest domyślny (3306)',
    'REMEMBER_ME': 'Pamiętaj mnie',
    'EMAIL_LOWERCASE': 'email',
    'PASSWORD_LOWERCASE': 'hasło',
    'TEST_SMTP_CONNECTION': 'Test połączenia SMTP',
    'SERVER_ERROR': 'Nie mogę połączyć się z serwerem.',
    'EMAIL_SERVER_ADDRESS': 'Adres serwera email',
    'EMAIL_SERVER_ADDRESS_DESCRIPTION': 'Adres, pod który będą odbierane i wysyłane maile',
};
