export default {
    'WELCOME': 'Witaj',
    'TICKETS': 'Zgłoszenia',
    'ARTICLES': 'Artykuły',
    'ACCOUNT': 'Konto',
    'SUBMIT': 'Wyślij',
    'EMAIL': 'Email',
    'PASSWORD': 'Hasło',
    'REPEAT_PASSWORD': 'Powtórz hasło',
    'LOG_IN': 'Zaloguj się',
    'SIGN_UP': 'Zarejestruj się',
    'FORGOT_PASSWORD': 'Zapomniałeś swoje hasło ?',
    'RECOVER_PASSWORD': 'Odzyskiwanie hasła',
    'RECOVER_SENT': 'Wysłano wiadomość e-mail z instrukcjami odzyskiwania.',
    'NEW_EMAIL': 'Nowy email',
    'FULL_NAME': 'Pełne imię i nazwisko',
    'OLD_PASSWORD': 'Stare hasło',
    'NEW_PASSWORD': 'Nowe hasło',
    'REPEAT_NEW_PASSWORD': 'Powtórz nowe hasło',
    'BACK_LOGIN_FORM': 'Powrót do formularza logowania',
    'VIEW_ARTICLES': 'Zobacz artykuły',
    'EDIT_PROFILE': 'Edytuj profil',
    'CLOSE_SESSION': 'Zamknij sesję',
    'CREATE_TICKET': 'Utwórz zgłoszenie',
    'TICKET_LIST': 'Lista zgłoszeń',
    'SUPPORT_CENTER': 'Centrum wsparcia',
    'DEPARTMENT': 'Department',
    'AUTHOR': 'Autor',
    'DATE': 'Data',
    'RESPOND': 'Odpowiedź',
    'RESPOND_TICKET': 'Odpowiedz na zgłoszenie',
    'CLOSE_TICKET': 'Zamknij zgłoszenie',
    'DELETE_TICKET': 'Usuń zgłoszenie',
    'NO_ATTACHMENT': 'Nie załączono pliku',
    'STAFF': 'Personel',
    'CUSTOMER': 'Klient',
    'YES': 'Tak',
    'NO': 'Nie',
    'CANCEL': 'Anuluj',
    'MY_ACCOUNT': 'Moje konto',
    'DASHBOARD': 'Tablica',
    'USERS': 'Klienci',
    'SETTINGS': 'Ustawienia',
    'STATISTICS': 'Statystyki',
    'LAST_ACTIVITY': 'Ostatnia aktywność',
    'MY_TICKETS': 'Moje zgłoszenia',
    'NEW_TICKETS': 'Nowe zgłoszenia',
    'ALL_TICKETS': 'Wszystkie zgłoszenia',
    'CUSTOM_RESPONSES': 'Odpowiedzi niestandardowe',
    'CUSTOM_TAGS': 'Tagi użytkowników',
    'LIST_USERS': 'Lista użytkowników',
    'BAN_USERS': 'Bany użytkowników',
    'LIST_ARTICLES': 'Lista artykułów',
    'STAFF_MEMBERS': 'Członkowie zespołu',
    'DEPARTMENTS': 'Departmenty',
    'SYSTEM_PREFERENCES': 'Ustawienia systemu',
    'ADVANCED_SETTINGS': 'Zaawansowane ustawienia',
    'EMAIL_TEMPLATES': 'Szablony email',
    'FILTERS_CUSTOM_FIELDS': 'Filtry i pola niestandardowe',
    'PRIORITY': 'Priorytety',
    'NUMBER': 'Numer',
    'HIGH': 'Wysoki',
    'MEDIUM': 'Średni',
    'LOW': 'Niski',
    'TITLE': 'Tytuł',
    'CONTENT': 'Zawartość',
    'SAVE': 'Zapisz',
    'DISCARD_CHANGES': 'Porzuć zmiany',
    'DELETE': 'Usuń',
    'LANGUAGE': 'Język',
    'OWNER': 'Właściciel',
    'OWNED': 'Własność',
    'STATUS': 'Status',
    'NONE': 'Żaden',
    'OPENED': 'Otwarte',
    'CLOSED': 'Zamknięte',
    'CLOSE': 'Zamknij',
    'RE_OPEN': 'Otwórz ponownie',
    'ASSIGN_TO_ME': 'Przypisz do mnie',
    'UN_ASSIGN': 'Usuń przypisanie',
    'VIEW_TICKET': 'Pokaż zgłoszenie',
    'VIEW_TICKET_DESCRIPTION': 'Sprawdź status zgłoszenia za pomocą numeru i wiadomości e-mail.',
    'SELECT_CUSTOM_RESPONSE': 'Wybierz odpowiedź...',
    'WARNING': 'Ostrzeżenie',
    'INFO': 'Informacja',
    'ALL_DEPARTMENTS': 'Wszystkie departamenty',
    'EMAIL_BANNED': 'Zablokowane adresy email',
    'UN_BAN': 'Wyłącz blokadę',
    'BAN_NEW_EMAIL': 'Zablokuj nowy adres email',
    'BAN_EMAIL': 'Zablokuj email',
    'EDIT_EMAIL': 'Edytuj email',
    'EDIT_PASSWORD': 'Edytuj hasło',
    'CHANGE_EMAIL': 'Zmień email',
    'CHANGE_PASSWORD': 'Zmień hasło',
    'NAME': 'Nazwa',
    'SIGNUP_DATE': 'Data rejestracji',
    'SEARCH_USERS': 'Szukaj użytkownika...',
    'SEARCH_EMAIL': 'Szukaj adresu email...',
    'USER_VIEW_TITLE': 'Użytkownik #{userId}',
    'EDIT_TOPIC': 'Edytuj temat',
    'ADD_TOPIC': 'Dodaj temat',
    'ICON': 'Ikona',
    'COLOR': 'Kolor',
    'ADD_NEW_ARTICLE': 'Dodaj nowy artykuł',
    'ADD_ARTICLE': 'Dodaj artykuł',
    'LAST_EDITED_IN': 'Ostatnia edycja {date}',
    'EDIT': 'Edytuj',
    'ADD_CUSTOM_TAG': 'Dodaj tag użytkownika',
    'NO_RESULTS': 'Brak wyników',
    'DELETE_AND_BAN': 'Usuń i zablokuj',
    'STAFF_LEVEL': 'Poziom personelu',
    'ASSIGNED': 'Przypisany',
    'ASSIGNED_TICKETS': '{tickets} przypisanych zgłoszeń',
    'CLOSED_TICKETS': '{tickets} zamkniętych zgłoszeń',
    'LAST_LOGIN': 'Ostatnio zalogowany',
    'ADD_NEW_STAFF': 'Dodaj nowy personel',
    'ADD_STAFF': 'Dodaj personel',
    'LEVEL': 'Poziom',
    'LEVEL_1': 'Poziom 1 (zgłoszenia)',
    'LEVEL_2': 'Poziom 2 (zgłoszenia + artykuły)',
    'LEVEL_3': 'Poziom 3 (zgłoszenia + artykuły + personel)',
    'LEVEL_1_DESCRIPTION': 'dostęp do zgłoszeń oraz użytkowników.',
    'LEVEL_2_DESCRIPTION': 'poziom 1 oraz tworzenie i edytowanie artykułów i niestandardowych odpowiedzi.',
    'LEVEL_3_DESCRIPTION': 'poziom 1, 2 oraz tworzenie / edytowanie personelu i zarządzanie systemem.',
    'UPDATE_EMAIL': 'Aktualizuj email',
    'UPDATE_PASSWORD': 'Aktualizuj hasło',
    'UPDATE_LEVEL': 'Aktualizuj poziom',
    'UPDATE_DEPARTMENTS': 'Aktualizuj departament',
    'EDIT_STAFF': 'Edytuj członka personelu',
    'ADD_DEPARTMENT': 'Dodaj departament',
    'UPDATE_DEPARTMENT': 'Aktualizuj departament',
    'TRANSFER_TICKETS_TO': 'Przenieś zgłoszenie do',
    'COMMENTS': 'Komentarze',
    'DELETE_STAFF_MEMBER': 'Usuń członka personelu',
    'MAINTENANCE_MODE': 'Tryb konderwacji',
    'MAINTENANCE_MODE_INFO': 'Trwa konserwacja, system czasowo wyłaczony.',
    'RECOVER_DEFAULT': 'Przywróc domyślne',
    'SUPPORT_CENTER_URL': 'Adres URL',
    'SUPPORT_CENTER_TITLE': 'Tutył systemu zgłoszeń',
    'SUPPORT_CENTER_LAYOUT': 'Wygląd systemu zgłoszeń',
    'DEFAULT_TIMEZONE': 'Domyślna strefa czasowa (GMT)',
    'NOREPLY_EMAIL': 'Adres email bez odpowiedzi (Noreplay)',
    'SMTP_USER': 'Użytkownik SMTP',
    'SMTP_SERVER': 'Serwer SMTP',
    'SMTP_PASSWORD': 'Hasło SMTP',
    'IMAP_USER': 'Użytkownik IMAP',
    'IMAP_SERVER': 'Serwer IMAP',
    'IMAP_PASSWORD': 'Hasło IMAP',
    'IMAP_TOKEN': 'Token IMAP',
    'IMAP_TOKEN_DESCRIPTION': 'Użyj tego tokena do uwierzytelnienia żądania odpytywania.',
    'PORT': 'Port',
    'RECAPTCHA_PUBLIC_KEY': 'Recaptcha Public Key',
    'RECAPTCHA_PRIVATE_KEY': 'Recaptcha Private Key',
    'ALLOW_FILE_ATTACHMENTS': 'Dozwolone załączniki',
    'MAX_SIZE_MB': 'Maksymalna wielkość (MB)',
    'UPDATE_SETTINGS': 'Ustawienia wysyłania',
    'DEFAULT_LANGUAGE': 'Domyślny język',
    'SUPPORTED_LANGUAGES': 'Wspierane języki',
    'SUPPORTED_LANGUAGES_INFO': 'Obsługiwane języki to języki, w których można zapisywać zgłoszenia.',
    'ALLOWED_LANGUAGES': 'Dozwolone języki',
    'ALLOWED_LANGUAGES_INFO': 'Dozwolone języki to języki, które mogą być używane przez użytkownika.',
    'SETTINGS_UPDATED': 'Ustawienia zostały zaktualizowane',
    'ON': 'On',
    'OFF': 'Off',
    'BOXED': 'Zapakowane',
    'FULL_WIDTH': 'Pełna szerokość',
    'LOAD_MORE': 'Pokaż więcej',
    'MY_NOTIFICATIONS': 'Moje powiadomienia',
    'ALL_NOTIFICATIONS': 'Wszystkie powiadomienia',
    'VERIFY_SUCCESS': 'Użytkownik zweryfikowany',
    'VERIFY_FAILED': 'Nie można zweryfikować',
    'ENABLE_USER_SYSTEM': 'Użyj systemu użytkownika dla klientów',
    'ENABLE_USER_REGISTRATION': 'Włącz rejestrację użytkowników',
    'INCLUDE_USERS_VIA_CSV': 'Importuj użytkowników z pliku CSV',
    'BACKUP_DATABASE': 'Kopia bazy danych',
    'DELETE_ALL_USERS': 'Usuń wszystkich użytkowników',
    'PLEASE_CONFIRM_PASSWORD': 'Proszę potwierdź Twoim hasłem przed zmianą ustawień',
    'REGISTRATION_API_KEYS': 'Zarejestruj klucz API',
    'NAME_OF_KEY': 'Nazwa klucza',
    'KEY': 'Klucz',
    'ADD_API_KEY': 'Dodaj klucz API',
    'NO_KEY_SELECTED': 'Nie wybrano klucza',
    'CHECK_TICKET': 'Sprawdź zgłoszenie',
    'ACTIVITY': 'Aktywne',
    'HOME': 'Start',
    'TICKET_NUMBER': 'Zgłoszenie numer',
    'NEXT': 'Następny',
    'SUBJECT': 'Temat',
    'SEND_EMAIL_ON_NEW_TICKET': 'Wyślij wiadomość email przy nowym zgłoszeniu',
    'STAFF_UPDATED': 'Członek personelu został zaktualizowany',
    'UPDATE': 'Aktualizuj',
    'NEVER': 'Nigdy',
    'HIMSELF': 'himself',
    'ADD_USER': 'Dodaj używkownika',
    'UPLOAD_FILE': 'Wyślij plik',
    'PRIVATE': 'Prywatne',
    'ENABLE_USER': 'Włącz użytkownika',
    'DISABLE_USER': 'Wyłącz użytkownika',
    'SHOW_CLOSED_TICKETS': 'Pokaż wszystkie zamknięte zgłoszenia',
    'IMAGE_HEADER_URL': 'Zdjęcie nagłówka (URL)',
    'IMAGE_HEADER_DESCRIPTION': 'Image that will be used as header of the email',
    'EMAIL_SETTINGS': 'Konfiguracje email',
    'ADDITIONAL_FIELDS': 'Dodatkowe pola',
    'NEW_CUSTOM_FIELD': 'Nowe pole niestandardowe',
    'TYPE': 'Typ',
    'SELECT_INPUT': 'Wybierz wejście',
    'TEXT_INPUT': 'Tekstowe wejście',
    'OPTION': 'Opcje {index}',
    'OPTIONS': 'Opcje',
    'FIELD_DESCRIPTION': 'Opis pola (opcjonalnie)',
    'DESCRIPTION_ADD_CUSTOM_TAG': 'tutaj możesz dodać nowy niestandardowy tag',
    'CUSTOM_FIELDS': 'Pola niestandardowe',

    'CHART_CREATE_TICKET': 'Zgłoszenie utworzone',
    'CHART_CLOSE': 'Zgłoszenia zamknięte',
    'CHART_SIGNUP': 'Zapisy',
    'CHART_COMMENT': 'Odpowiedzi',
    'CHART_ASSIGN': 'Przydzielony',

    //ACTIVITIES
    'ACTIVITY_COMMENT': 'komentarze zgłoszeń',
    'ACTIVITY_ASSIGN': 'przydzielone zgłoszenia',
    'ACTIVITY_UN_ASSIGN': 'nie przydzielone zgłoszenia',
    'ACTIVITY_CLOSE': 'zamknięte zgłoszenia',
    'ACTIVITY_CREATE_TICKET': 'stwórz zgłoszenie',
    'ACTIVITY_RE_OPEN': 'ponownie otworzone zgłoszenie',
    'ACTIVITY_DEPARTMENT_CHANGED': 'zmień departament zgłoszenia',
    'ACTIVITY_PRIORITY_CHANGED': 'zmień priorytet zgłoszenia',

    'ACTIVITY_EDIT_SETTINGS': 'edytowano ustawienia',
    'ACTIVITY_SIGNUP': 'zalogowano',
    'ACTIVITY_ADD_TOPIC': 'dodano temat',
    'ACTIVITY_ADD_ARTICLE': 'dodano artykuł',
    'ACTIVITY_DELETE_TOPIC': 'usunięto temat',
    'ACTIVITY_DELETE_ARTICLE': 'usunięto artykuł',
    'ACTIVITY_EDIT_ARTICLE': 'edytowano artykuł',
    'ACTIVITY_ADD_STAFF': 'dodano personel',
    'ACTIVITY_ADD_DEPARTMENT': 'dodano departament',
    'ACTIVITY_DELETE_DEPARTMENT': 'usunięto department',
    'ACTIVITY_EDIT_DEPARTMENT': 'edytowano department',
    'ACTIVITY_ADD_CUSTOM_RESPONSE': 'dodano niestandardową odpowiedź',
    'ACTIVITY_DELETE_CUSTOM_RESPONSE': 'usunięto niestandardową odpowiedź',
    'ACTIVITY_EDIT_CUSTOM_RESPONSE': 'edytowana odpowiedź niestandardowa',
    'ACTIVITY_BAN_USER': 'uzytkownik zablokowany',
    'ACTIVITY_DELETE_USER': 'użytkownik usunięty',
    'ACTIVITY_UN_BAN_USER': 'użytkownik odblokowany',

    'SERVER_REQUIREMENTS': 'Server requirements',
    'DATABASE_CONFIGURATION': 'Database configuration',
    'ADMIN_SETUP': 'Admin setup',
    'COMPLETED': 'Completed',
    'INSTALL_HEADER_TITLE': 'OpenSupports Installation Wizard',
    'INSTALL_HEADER_DESCRIPTION': 'This wizard will help you to configure and install OpenSupports on your website',
    'SELECT_LANGUAGE': 'Select language',
    'REQUIREMENT': 'Requirement',
    'VALUE': 'Value',
    'REFRESH': 'Refresh',
    'USER_SYSTEM': 'User System',
    'PREVIOUS': 'Previous',
    'DATABASE_HOST': 'MySQL server',
    'DATABASE_PORT': 'MySQL server port',
    'DATABASE_NAME': 'MySQL database name',
    'DATABASE_USER': 'MySQL user',
    'DATABASE_PASSWORD': 'MySQL password',
    'ADMIN_NAME': 'Admin account name',
    'ADMIN_EMAIL': 'Admin account email',
    'ADMIN_PASSWORD': 'Admin account password',
    'ADMIN_PASSWORD_DESCRIPTION': 'Please remember this password. It is needed for accessing the admin panel. You can change it later.',
    'INSTALLATION_COMPLETED': 'Installation completed.',
    'INSTALLATION_COMPLETED_DESCRIPTION': 'The installation of OpenSupports is completed. Redirecting to admin panel...',

    'STEP_TITLE': 'Step {current} of {total} - {title}',
    'STEP_1_DESCRIPTION': 'Select your preferred language for the installation wizard.',
    'STEP_2_DESCRIPTION': 'Here are listed the requirements for running OpenSupports. Please make sure that all requirements are satisfied.',
    'STEP_3_DESCRIPTION': 'Please fill the MySQL database configuration.',
    'STEP_4_DESCRIPTION': 'Please select your user system preferences.',
    'STEP_5_DESCRIPTION': 'Please fill your general system preferences.',
    'STEP_6_DESCRIPTION': 'Please configure the administrator account.',
    'STEP_7_DESCRIPTION': 'Installation is completed.',

    //VIEW DESCRIPTIONS
    'CREATE_TICKET_DESCRIPTION': 'This is a form for creating tickets. Fill the form and send us your issues/doubts/suggestions. Our support system will answer it as soon as possible.',
    'TICKET_LIST_DESCRIPTION': 'Here you can find a list of all tickets you have sent to our support team.',
    'TICKETS_DESCRIPTION': 'Send ticket through our support center and get response of your doubts, suggestions and issues.',
    'ARTICLES_DESCRIPTION': 'Take a look to our articles about common issues, guides and documentation.',
    'ACCOUNT_DESCRIPTION': 'All your tickets are stored in your account\'s profile. Keep track of all your tickets you send to our staff team.',
    'SUPPORT_CENTER_DESCRIPTION': 'Welcome to our support center. You can contact us through a tickets system. Your tickets will be answered by our staff.',
    'CUSTOM_RESPONSES_DESCRIPTION': 'Custom responses are automated responses for common problems',
    'CUSTOM_TAGS_DESCRIPTION': 'Here you can view manage the custom tags for tickets to identify them better',
    'MY_TICKETS_DESCRIPTION': 'Here you can view the tickets you are responsible for.',
    'NEW_TICKETS_DESCRIPTION': 'Here you can view all the new tickets that are not assigned by anyone.',
    'ALL_TICKETS_DESCRIPTION': 'Here you can view the tickets of the departments you are assigned.',
    'TICKET_VIEW_DESCRIPTION': 'This ticket has been sent by a customer. Here you can respond or assign the ticket',
    'BAN_USERS_DESCRIPTION': 'Here you can see a list of banned emails, you can un-ban them or add more emails to the list.',
    'LIST_USERS_DESCRIPTION': 'This is the list of users that are registered in this platform. You can search for someone in particular, delete it or ban it.',
    'USER_VIEW_DESCRIPTION': 'Here you can find all the information about an user and all the tickets sent by the user. You can also delete or ban it.',
    'DELETE_USER_DESCRIPTION': 'The user will not be able to log in aging and all its tickets will be erased. Also, the email can not be used any more.',
    'DELETE_TOPIC_DESCRIPTION': 'By deleting the topic, all articles on it will be erased.',
    'EDIT_TOPIC_DESCRIPTION': 'Here you can change the name, the icon and the icon color of the topic.',
    'ADD_ARTICLE_DESCRIPTION': 'Here you can add an article that will be available for every user. It will be added inside the category {category}.',
    'LIST_ARTICLES_DESCRIPTION': 'This is a list of articles that includes information about our services.',
    'ADD_TOPIC_DESCRIPTION': 'Here you can add a topic that works as a category for articles.',
    'DELETE_ARTICLE_DESCRIPTION': 'You\'re going to delete this article forever.',
    'STAFF_MEMBERS_DESCRIPTION': 'Here you can see who are your staff members.',
    'ADD_STAFF_DESCRIPTION': 'Here you can add staff members to your teams.',
    'EDIT_STAFF_DESCRIPTION': 'Here you can edit information about a staff member.',
    'MY_ACCOUNT_DESCRIPTION': 'Here you can edit information about you.',
    'DEPARTMENTS_DESCRIPTION': 'A department is a group where the tickets can go. They are used to categorize the tickets. You can assign them to other staff members.',
    'MAINTENANCE_MODE_DESCRIPTION': 'The support system is in maintenance mode, thus unavailable at the moment. We will come back as soon as possible.',
    'EMAIL_TEMPLATES_DESCRIPTION': 'Here you can edit the templates of the emails that will be sent to users. Remember that the double brackets curly braces indicate a variable value. For example, \'name\' represents the user\'s name.',
    'SYSTEM_PREFERENCES_DESCRIPTION': 'Here you can edit the preferences of the system.',
    'VERIFY_SUCCESS_DESCRIPTION': 'You user has been verified correctly. You can log in now.',
    'VERIFY_FAILED_DESCRIPTION': 'The verification could not be done.',
    'STATISTICS_DESCRIPTION': 'Here you can view statistics related to tickets and signups.',
    'ADVANCED_SETTINGS_DESCRIPTION': 'Here you can change the advanced settings of your system. Please be careful, the changes you make can not be reversed.',
    'USER_SYSTEM_DISABLED': 'User system has been disabled',
    'USER_SYSTEM_ENABLED': 'User system has been enabled',
    'REGISTRATION_DISABLED': 'Registration has been disabled',
    'REGISTRATION_ENABLED': 'Registration has been enabled',
    'ADD_API_KEY_DESCRIPTION': 'Insert the name and a registration api key will be generated.',
    'SIGN_UP_VIEW_DESCRIPTION': 'Here you can create an account for our support center. It is required to send tickets and see documentation.',
    'EDIT_PROFILE_VIEW_DESCRIPTION': 'Here you can edit your user by changing your email or your password.',
    'ENABLE_USER_SYSTEM_DESCRIPTION': 'Enable/disable the use of an user system. If you disable it, all users will be deleted but the tickets will be kept. If you enable it, the users of existent tickets will be created.',
    'CSV_DESCRIPTION': 'The CSV file must have 3 columns: email, password, name. There is no limit in row count. It will be created one user per row in the file.',
    'SMTP_SERVER_DESCRIPTION': 'The configuration of the SMTP server allows the application to send mails. If you do not configure it, no emails will be sent by OpenSupports.',
    'IMAP_SERVER_DESCRIPTION': 'The configuration of the IMAP server allows the application to create tickets from the emails sent to a mailbox.',
    'ENABLE_USER_DESCRIPTION': 'This action allows the user to sign in and create tickets.',
    'DISABLE_USER_DESCRIPTION': 'User will be disabled and will not be able to sign in and create tickets.',
    'PRIVATE_RESPONSE_DESCRIPTION': 'This response will only be seen by staff members',
    'PRIVATE_TOPIC_DESCRIPTION': 'This topic will only be seen by staff members',
    'PRIVATE_DEPARTMENT_DESCRIPTION': 'This department will only be seen by staff members',
    'EMAIL_SETTINGS_DESCRIPTION': 'Here you can edit the settings for receiving and sending email to your customers.',
    'IMAP_POLLING_DESCRIPTION': 'Inbox checking will not be done automatically by OpenSupports. You have to make POST requests periodically to this url to process the emails: {url}',
    'NEW_CUSTOM_FIELD_DESCRIPTION': 'Here you can create a custom field for an user, it can be a blank text box or a fixed set of options.',
    'CUSTOM_FIELDS_DESCRIPTION': 'Custom fields are defined additional fields the users are able to fill to provide more information about them.',

    //ERRORS
    'EMAIL_OR_PASSWORD': 'Email or password invalid',
    'EMAIL_NOT_EXIST': 'Email does not exist',
    'ERROR_EMPTY': 'Invalid value',
    'ERROR_PASSWORD': 'Invalid password',
    'ERROR_NAME': 'Invalid name',
    'ERROR_TITLE': 'Invalid title',
    'ERROR_EMAIL': 'Invalid email',
    'ERROR_CONTENT_SHORT': 'Content too short',
    'PASSWORD_NOT_MATCH': 'Password does not match',
    'INVALID_RECOVER': 'Invalid recover data',
    'TICKET_SENT_ERROR': 'An error occurred while trying to create the ticket.',
    'TICKET_COMMENT_ERROR': 'An error occurred while trying to add the comment.',
    'NO_PERMISSION': 'You\'ve no permission to access to this page.',
    'INVALID_USER': 'User id is invalid',
    'ERROR_RETRIEVING_TICKETS': 'An error occurred while trying to retrieve tickets.',
    'ERROR_RETRIEVING_USERS': 'An error occurred while trying to retrieve users.',
    'ERROR_RETRIEVING_BAN_LIST': 'An error occurred while trying to retrieve the list of banned emails.',
    'ERROR_BANNING_EMAIL': 'An error occurred while trying to ban the email.',
    'ERROR_RETRIEVING_ARTICLES': 'An error occurred while trying to retrieve articles.',
    'ERROR_LIST': 'Select at least one',
    'ERROR_URL': 'Invalid URL',
    'UNVERIFIED_EMAIL': 'Email is not verified yet',
    'ERROR_UPDATING_SETTINGS': 'An error occurred while trying to update settings',
    'INVALID_EMAIL_OR_TICKET_NUMBER': 'Invalid email or ticket number',
    'INVALID_FILE': 'Invalid file',
    'ERRORS_FOUND': 'Errors found',
    'ERROR_IMAGE_SIZE': 'No image can have a size greater than {size} MB',
    'USER_DISABLED': 'This account is disabled.',
    'INVALID_SYNTAX': 'Invalid syntax.',
    'DEPARTMENT_PRIVATE_TICKETS': 'This department has tickets created by non-staff and it can not be private',
    'CURRENTLY_UNAVAILABLE': 'Currently unavailable',

    //MESSAGES
    'SIGNUP_SUCCESS': 'You have registered successfully in our support system.',
    'TICKET_SENT': 'Ticket has been created successfully.',
    'VALID_RECOVER': 'Password recovered successfully',
    'EMAIL_EXISTS': 'Email already exists',
    'ARE_YOU_SURE': 'Confirm action',
    'EMAIL_WILL_CHANGE': 'The current email will be changed',
    'PASSWORD_WILL_CHANGE': 'The current password will be changed',
    'EMAIL_CHANGED': 'Email has been changed successfully',
    'PASSWORD_CHANGED': 'Password has been changed successfully',
    'OLD_PASSWORD_INCORRECT': 'Old password is incorrect',
    'WILL_LOSE_CHANGES': 'You haven\'t save. Your changes will be lost.',
    'WILL_DELETE_CUSTOM_RESPONSE': 'The custom response will be deleted.',
    'WILL_DELETE_DEPARTMENT': 'The department will be deleted. All the tickets will be transfer to the department selected.',
    'NO_STAFF_ASSIGNED': 'No staff member is assigned to this department.',
    'NO_DEPARTMENT_ASSIGNED': 'No ticket department is assigned you.',
    'LEVEL_UPDATED': 'Level has been updated successfully.',
    'DEPARTMENTS_UPDATED': 'Departments have been updated successfully.',
    'FAILED_EDIT_STAFF': 'An error occurred while trying to edit staff member.',
    'EMAIL_BANNED_SUCCESSFULLY': 'Email has been banned successfully',
    'WILL_DELETE_STAFF': 'This staff member will be deleted and all its tickets will be unassigned.',
    'WILL_RECOVER_EMAIL_TEMPLATE': 'This email template will be recover to it\'s default value on this language.',
    'SUCCESS_IMPORTING_CSV_DESCRIPTION': 'CSV File has been imported successfully',
    'SUCCESS_DELETING_ALL_USERS': 'Users have beend deleted successfully',
    'SUCCESSFUL_CONNECTION': 'Successful connection',
    'UNSUCCESSFUL_CONNECTION': 'Unsuccessful connection',
    'SERVER_CREDENTIALS_WORKING': 'Server credentials are working correctly',
    'DELETE_CUSTOM_FIELD_SURE': 'Some users may be using this field. Are you sure you want to delete it?',

    'LAST_7_DAYS': 'Ostatnie 7 dni',
    'LAST_30_DAYS': 'Ostatnie 30 dni',
    'LAST_90_DAYS': 'Ostatnie 90 dni',
    'LAST_365_DAYS': 'Ostatnie 365 dni',

    'TEST': 'Test',
    'ACTIVITY_COMMENT_THIS': 'commented this ticket',
    'ACTIVITY_ASSIGN_THIS': 'assigned this ticket to',
    'ACTIVITY_UN_ASSIGN_THIS': 'unassigned this ticket to',
    'ACTIVITY_CLOSE_THIS': 'closed this ticket',
    'ACTIVITY_CREATE_TICKET_THIS': 'created this ticket',
    'ACTIVITY_RE_OPEN_THIS': 'reopened this ticket',
    'ACTIVITY_DEPARTMENT_CHANGED_THIS': 'changed department of this ticket to ',
    'ACTIVITY_PRIORITY_CHANGED_THIS': 'changed priority of this ticket to',
    'DATE_PREFIX': 'on',
    'LEFT_EMPTY_DATABASE': 'Zostaw pusty jeśli mam utworzyć pustą bazę danych automatycznie',
    'DEFAULT_PORT': 'Zostaw pusty jeśli port jest domyślny (3306)',
    'REMEMBER_ME': 'Pamiętaj mnie',
    'EMAIL_LOWERCASE': 'email',
    'PASSWORD_LOWERCASE': 'hasło',
    'TEST_SMTP_CONNECTION': 'Test połączenia SMTP',
    'SERVER_ERROR': 'Nie mogę połączyć się z serwerem.',
    'EMAIL_SERVER_ADDRESS': 'Adres serwera email',
    'EMAIL_SERVER_ADDRESS_DESCRIPTION': 'Adres, pod który będą odbierane i wysyłane maile',
};
